# Generated by Django 3.2.9 on 2021-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
